{ pkgs, ... }:

{
  environment.systemPackages = [
    pkgs.vim
    pkgs.firefox
    pkgs.firefox-wayland
    pkgs.curl
    pkgs.htop
    pkgs.hyprland
    pkgs.hyprlock
    pkgs.hypridle 
    pkgs.kitty
    pkgs.foot
    pkgs.pciutils
    pkgs.waybar
    pkgs.hyprpaper
    pkgs.wofi
    pkgs.neovim
    pkgs.xdg-utils
    pkgs.xdg-desktop-portal
    pkgs.xdg-desktop-portal-wlr
    pkgs.xdg-desktop-portal-gtk
    pkgs.xdg-desktop-portal-hyprland
    pkgs.wlr-randr
    pkgs.wl-clipboard
    pkgs.hyprland-protocols
    pkgs.grim
    pkgs.slurp
    pkgs.uwsm
    pkgs.nwg-look
    pkgs.fastfetch
    pkgs.git
    pkgs.gcc
    pkgs.adwaita-qt
    pkgs.adwaita-qt6
    pkgs.zip
    pkgs.unzip
    pkgs.pulseaudio
    pkgs.brightnessctl
    pkgs.pavucontrol
  ];
}
